//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDetails_log
    {
        public int applicationId { get; set; }
        public Nullable<int> schemeId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string formNo { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public string marritalStatus { get; set; }
        public string fatherHusbandName { get; set; }
        public string motherName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string signingAuthority { get; set; }
        public string registeredOffice { get; set; }
        public string correspondanceAdd { get; set; }
        public string permanentAdd { get; set; }
        public string mobileNumberP1 { get; set; }
        public string mobileNumberP2 { get; set; }
        public string phoneNumberP1 { get; set; }
        public string phoneNumberP2 { get; set; }
        public string faxNumberP1 { get; set; }
        public string faxNumberP2 { get; set; }
        public string email { get; set; }
        public Nullable<int> occupationId { get; set; }
        public Nullable<int> quotaId { get; set; }
        public Nullable<int> religionId { get; set; }
        public string pan { get; set; }
        public Nullable<decimal> annualIncome { get; set; }
        public Nullable<int> registrationId { get; set; }
        public string isAllotted { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string tFirstName { get; set; }
        public string tMiddleName { get; set; }
        public string tLastName { get; set; }
        public string tGender { get; set; }
        public string tMarritalStatus { get; set; }
        public string tFatherHusbandName { get; set; }
        public string tMotherName { get; set; }
        public Nullable<System.DateTime> tDateOfBirth { get; set; }
        public string tSigningAuthority { get; set; }
        public string tRegisteredOffice { get; set; }
        public string tCorrespondanceAdd { get; set; }
        public string tPermanentAdd { get; set; }
        public string tMobileNumber { get; set; }
        public string tPhoneNumber { get; set; }
        public string tEmail { get; set; }
        public Nullable<int> tOccupationId { get; set; }
        public string tPan { get; set; }
        public Nullable<decimal> tAnnualIncome { get; set; }
        public Nullable<bool> tFlag { get; set; }
        public string tType { get; set; }
        public string tSubType { get; set; }
        public Nullable<System.DateTime> tDate { get; set; }
        public string T_Company_Name { get; set; }
        public string tenderforproperty { get; set; }
        public Nullable<int> OldRegistrationId { get; set; }
    }
}
