//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditBBBSLocation
    {
        public int BBBSLocationAuditId { get; set; }
        public int BBBSLocationId { get; set; }
        public string LocationName { get; set; }
        public string LocationLine1 { get; set; }
        public string LocationLine2 { get; set; }
        public string LocationLine3 { get; set; }
        public string LocationLine4 { get; set; }
        public string LocationLine5 { get; set; }
        public string AdditionalInformation { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateEnteredOn { get; set; }
    }
}
