//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditItemsLeftbehind
    {
        public int ItemsLeftbehindAuditId { get; set; }
        public int ItemsLeftbehindId { get; set; }
        public int DonationId { get; set; }
        public int DriverId { get; set; }
        public int DriverTypeId { get; set; }
        public int RouteId { get; set; }
        public System.DateTime TimeCalledIn { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsCND { get; set; }
        public string ItemsDriverLeftbehind { get; set; }
        public Nullable<int> CBCodeId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DataEnteredOn { get; set; }
    }
}
