//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyDriverRoute
    {
        public int DailyDriverRouteId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public int DriverId { get; set; }
        public int DriverTypeId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<int> DonateDestinationId { get; set; }
        public Nullable<decimal> StoreTicketNumber { get; set; }
        public Nullable<int> SoftWeight { get; set; }
        public Nullable<int> HardWeight { get; set; }
        public Nullable<int> BookWeight { get; set; }
        public Nullable<int> TotalWeight { get; set; }
    
        public virtual DonateDestination DonateDestination { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual DriverType DriverType { get; set; }
        public virtual PickupSchedule PickupSchedule { get; set; }
    }
}
