//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_test
    {
        public Nullable<int> rid { get; set; }
        public Nullable<System.DateTime> functionaldate { get; set; }
        public Nullable<int> departmentid { get; set; }
        public int propertyId { get; set; }
    }
}
