//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date_View
    {
        public int rid { get; set; }
        public string AlloteName { get; set; }
        public Nullable<decimal> actualArea { get; set; }
        public string Sector { get; set; }
        public string block { get; set; }
        public string propertyno { get; set; }
    }
}
