//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation()
        {
            this.DonationReceipts = new HashSet<DonationReceipt>();
            this.DonationTransactions = new HashSet<DonationTransaction>();
            this.PickupReminders = new HashSet<PickupReminder>();
            this.DonationPickupDates = new HashSet<DonationPickupDate>();
            this.DWAReports = new HashSet<DWAReport>();
            this.ItemsLeftbehinds = new HashSet<ItemsLeftbehind>();
            this.MassRescheduleStatus = new HashSet<MassRescheduleStatu>();
        }
    
        public int DonationId { get; set; }
        public int DonorId { get; set; }
        public Nullable<int> DonorAddressId { get; set; }
        public int DonationTypeId { get; set; }
        public int DWAStatusId { get; set; }
        public Nullable<int> ItemWeight { get; set; }
        public int DonorSourceId { get; set; }
        public int DonationStatusId { get; set; }
        public Nullable<int> ItemLocationId { get; set; }
        public Nullable<int> PickupPriorityId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public bool IsDWA { get; set; }
        public bool IsDonationRouteException { get; set; }
        public bool IsMultipleDates { get; set; }
        public string Comments { get; set; }
        public string Instructions { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int DateKey { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsMissedOrRescheduled { get; set; }
        public string MissedOrRescheduledReason { get; set; }
        public bool IsCancel { get; set; }
        public bool IsDoNotCall { get; set; }
    
        public virtual DateDimension DateDimension { get; set; }
        public virtual DonationType DonationType { get; set; }
        public virtual DWAStatu DWAStatu { get; set; }
        public virtual ItemLocation ItemLocation { get; set; }
        public virtual PickupPriority PickupPriority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationReceipt> DonationReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationTransaction> DonationTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupReminder> PickupReminders { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual PickupSchedule PickupSchedule { get; set; }
        public virtual DonationSource DonationSource { get; set; }
        public virtual DonationStatu DonationStatu { get; set; }
        public virtual DonorAddress DonorAddress { get; set; }
        public virtual PickupSchedule PickupSchedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonationPickupDate> DonationPickupDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DWAReport> DWAReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsLeftbehind> ItemsLeftbehinds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassRescheduleStatu> MassRescheduleStatus { get; set; }
    }
}
