//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationReceipt
    {
        public int DonationReceiptId { get; set; }
        public int DonationId { get; set; }
        public int DonorId { get; set; }
        public int EmailTemplateId { get; set; }
        public bool IsEmail { get; set; }
        public bool IsPrint { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual EmailTemplate EmailTemplate { get; set; }
    }
}
