//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationTransaction
    {
        public int DonationTransactionId { get; set; }
        public int DonationId { get; set; }
        public string Action { get; set; }
        public string Comments { get; set; }
        public int DonationStatusId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int DateKey { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual DonationStatu DonationStatu { get; set; }
    }
}
