//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWAReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DWAReport()
        {
            this.DWAAuditHistories = new HashSet<DWAAuditHistory>();
        }
    
        public int DWAReportId { get; set; }
        public int DonorId { get; set; }
        public System.DateTime DonationTimestamp { get; set; }
        public System.DateTime PickupDate { get; set; }
        public int DriverId { get; set; }
        public bool MissedReschedule { get; set; }
        public int DWAStatusId { get; set; }
        public int DonationId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DWAAuditHistory> DWAAuditHistories { get; set; }
        public virtual DWAStatu DWAStatu { get; set; }
    }
}
