//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ind162162
    {
        public int onlineapplicationId { get; set; }
        public string OldFormNo { get; set; }
        public string Name { get; set; }
        public string Applicant_Type { get; set; }
        public string Signing_Authority { get; set; }
        public string Permanent_Address { get; set; }
        public string Registered_Office { get; set; }
        public string Correspondance_Address { get; set; }
        public string Mobile_No { get; set; }
        public string Phone_No { get; set; }
        public string email { get; set; }
        public string Quota { get; set; }
        public string pan { get; set; }
        public Nullable<decimal> annualIncome { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string Company_Type { get; set; }
        public string Area { get; set; }
        public string Refund_Bank_Name { get; set; }
        public string refundInFavourOf { get; set; }
        public string RefundAccountNo_ { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string IFSC_Code { get; set; }
        public string BanchName { get; set; }
        public string AadharNumber { get; set; }
        public string FormCategory { get; set; }
        public string FormSubCategory { get; set; }
        public string projectcost { get; set; }
        public string projecttimeempl { get; set; }
        public string GST { get; set; }
        public string BankName { get; set; }
        public string Payment_Type { get; set; }
        public string ChallanStatus { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
