//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngenuityServiceConfiguration
    {
        public int IngenuityServiceConfigurationId { get; set; }
        public bool IsServiceTriggeredByUI { get; set; }
        public System.DateTime ServiceTriggeredByUIStartTime { get; set; }
        public System.DateTime ServiceTriggeredByUIEndTime { get; set; }
        public bool IsServiceAutoTriggered { get; set; }
        public System.DateTime ServiceAutoTriggeredStartTime { get; set; }
        public System.DateTime ServiceAutoTriggeredEndTime { get; set; }
        public bool IsErrorDuringLastRun { get; set; }
        public string ErrorDescription { get; set; }
        public int UISessionUserId { get; set; }
        public string UISessionUserName { get; set; }
        public string UISessionUserEmail { get; set; }
        public int ServiceAutoUserId { get; set; }
        public string ServiceAutoUserName { get; set; }
        public string ServiceAutoUserEmail { get; set; }
    }
}
