//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngenuityFileUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngenuityFileUpload()
        {
            this.IngenuityFileUserErrors = new HashSet<IngenuityFileUserError>();
            this.IngenuityFileUserSuccesses = new HashSet<IngenuityFileUserSuccess>();
        }
    
        public int LogId { get; set; }
        public string FileName { get; set; }
        public string RouteName { get; set; }
        public System.DateTime PickupDate { get; set; }
        public string StatusUpload { get; set; }
        public string ErrorMessage { get; set; }
        public string StatusParse { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngenuityFileUserError> IngenuityFileUserErrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngenuityFileUserSuccess> IngenuityFileUserSuccesses { get; set; }
    }
}
