//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngenuityFileUserError
    {
        public int ErrorId { get; set; }
        public int LogId { get; set; }
        public int RowNo { get; set; }
        public string AddressCombined { get; set; }
        public string AddressCombinedError { get; set; }
        public Nullable<int> AddressNumber { get; set; }
        public string AddressNumberError { get; set; }
        public string Street { get; set; }
        public string StreetError { get; set; }
        public string ResidenceType { get; set; }
        public string ResidenceTypeError { get; set; }
        public string LocationXCrossStreet { get; set; }
        public string ItemLocation { get; set; }
        public string ItemLocationError { get; set; }
        public string CrossStreet { get; set; }
        public string CrossStreetError { get; set; }
        public string Instructions { get; set; }
        public string LastName { get; set; }
        public string LastNameError { get; set; }
        public int Phone { get; set; }
        public string PhoneError { get; set; }
        public string Town { get; set; }
        public string TownError { get; set; }
        public int ZipCode { get; set; }
        public string ZipCodeError { get; set; }
        public string Email { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual IngenuityFileUpload IngenuityFileUpload { get; set; }
    }
}
