//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngenuitySuccessData
    {
        public long IngenuitySuccessDataId { get; set; }
        public string PhoneNumber { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string HouseNumber { get; set; }
        public string Street { get; set; }
        public string PhAPT { get; set; }
        public string LocationCrossStreet { get; set; }
        public string LastName { get; set; }
        public string Town { get; set; }
        public int Status { get; set; }
        public string StatusDescription { get; set; }
        public string Instructions { get; set; }
        public int BatchId { get; set; }
        public string Route { get; set; }
        public System.DateTime PickupDate { get; set; }
        public string ResidenceType { get; set; }
        public string ItemLocation { get; set; }
        public string CrossStreet { get; set; }
        public System.DateTime ValidatedDate { get; set; }
    }
}
