//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngenuityOutput
    {
        public long IngenuityOutputId { get; set; }
        public string PhoneNumber { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string HouseNumber { get; set; }
        public string Street { get; set; }
        public string PhAPT { get; set; }
        public string LocationCrossStreet { get; set; }
        public string LastName { get; set; }
        public string Town { get; set; }
        public string Route { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
    }
}
