//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassRescheduleStatu
    {
        public int MassRescheduleStatusId { get; set; }
        public int MassRescheduleId { get; set; }
        public int DonorId { get; set; }
        public Nullable<int> DonationId { get; set; }
        public int ScheduleId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual MassReschedule MassReschedule { get; set; }
        public virtual PickupSchedule PickupSchedule { get; set; }
    }
}
