//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassReschedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MassReschedule()
        {
            this.MassRescheduleStatus = new HashSet<MassRescheduleStatu>();
        }
    
        public int MassRescheduleId { get; set; }
        public int ScheduleId { get; set; }
        public int EmailTemplateId { get; set; }
        public System.DateTime RescheduledPickupDate { get; set; }
        public int RescheduledDateKey { get; set; }
        public Nullable<int> RescheduledScheduleId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual EmailTemplate EmailTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassRescheduleStatu> MassRescheduleStatus { get; set; }
        public virtual PickupSchedule PickupSchedule { get; set; }
        public virtual PickupSchedule PickupSchedule1 { get; set; }
    }
}
