//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class oldscheme
    {
        public int OnlineApplicationid { get; set; }
        public string Old_Form_No { get; set; }
        public Nullable<int> schemeid { get; set; }
        public string SchemeName { get; set; }
        public string Name { get; set; }
        public string ApplicantType { get; set; }
        public string Signing_Authority { get; set; }
        public string Mobile_No { get; set; }
        public string Phone_No { get; set; }
        public string Email { get; set; }
        public string Pan { get; set; }
        public Nullable<System.DateTime> Application_Date { get; set; }
        public string Company_Type { get; set; }
        public string Area { get; set; }
        public string Refund_Bank_Name { get; set; }
        public string refund_InFavour_Of { get; set; }
        public string Refund_Account_No_ { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string IFSC_Code { get; set; }
        public string Banch_Name { get; set; }
        public string Aadhar_Number { get; set; }
        public string GST { get; set; }
        public Nullable<decimal> ApplicationFee { get; set; }
        public Nullable<decimal> EarnestMoney { get; set; }
        public Nullable<decimal> ProcessingCharge { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> FormSGST { get; set; }
        public Nullable<decimal> FormCGST { get; set; }
        public Nullable<decimal> ProcessingSGST { get; set; }
        public Nullable<decimal> ProcessingCGST { get; set; }
        public string Projectname { get; set; }
        public string projectcost { get; set; }
        public string Photographfilename { get; set; }
        public string BankName { get; set; }
        public string Payment_Type { get; set; }
        public string ChallanStatus { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
