//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneScript
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhoneScript()
        {
            this.PickupReminders = new HashSet<PickupReminder>();
            this.PickupReminderHistories = new HashSet<PickupReminderHistory>();
        }
    
        public int PhoneScriptId { get; set; }
        public string Title { get; set; }
        public string Script { get; set; }
        public bool LeaveVoicemail { get; set; }
        public bool IsActive { get; set; }
        public int RedirectNumberId { get; set; }
        public int PhoneResponseTypeId { get; set; }
        public bool Display { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual RedirectNumberFromPhone RedirectNumberFromPhone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupReminder> PickupReminders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupReminderHistory> PickupReminderHistories { get; set; }
    }
}
