//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupCallLog
    {
        public long PickupCallLogId { get; set; }
        public string CallSID { get; set; }
        public string FromNumber { get; set; }
        public string ToNumber { get; set; }
        public Nullable<System.DateTime> CallDateTime { get; set; }
        public Nullable<System.DateTime> CallStartTime { get; set; }
        public Nullable<System.DateTime> CallEndTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> CallStatus { get; set; }
        public string CallStatusDetail { get; set; }
        public string CallAPICompleteResponse { get; set; }
    }
}
