//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupReminderHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickupReminderHistory()
        {
            this.PickupReminders = new HashSet<PickupReminder>();
        }
    
        public int PickupReminderId { get; set; }
        public string PickupReminderName { get; set; }
        public Nullable<System.DateTime> PickupReminderDate { get; set; }
        public Nullable<int> PickupReminderStatusId { get; set; }
        public Nullable<int> CompletedCalls { get; set; }
        public Nullable<int> PhoneScriptId { get; set; }
        public bool IsMassReminder { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual PhoneScript PhoneScript { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupReminder> PickupReminders { get; set; }
        public virtual PickupReminderStatu PickupReminderStatu { get; set; }
    }
}
