//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickupSchedule()
        {
            this.DailyDriverRoutes = new HashSet<DailyDriverRoute>();
            this.DailyDriverScannedCopies = new HashSet<DailyDriverScannedCopy>();
            this.Donations = new HashSet<Donation>();
            this.Donations1 = new HashSet<Donation>();
            this.FillerBlastHistories = new HashSet<FillerBlastHistory>();
            this.MassReschedules = new HashSet<MassReschedule>();
            this.MassReschedules1 = new HashSet<MassReschedule>();
            this.MassRescheduleStatus = new HashSet<MassRescheduleStatu>();
            this.PickupReminders = new HashSet<PickupReminder>();
            this.PickupScheduleRoutes = new HashSet<PickupScheduleRoute>();
        }
    
        public int ScheduleId { get; set; }
        public int RouteId { get; set; }
        public int PickupRouteTypeId { get; set; }
        public int MaxPickup { get; set; }
        public Nullable<int> CurrentCount { get; set; }
        public Nullable<int> NoPickup { get; set; }
        public int SuccessRate { get; set; }
        public Nullable<int> DateKey { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyDriverRoute> DailyDriverRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyDriverScannedCopy> DailyDriverScannedCopies { get; set; }
        public virtual DateDimension DateDimension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FillerBlastHistory> FillerBlastHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassReschedule> MassReschedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassReschedule> MassReschedules1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassRescheduleStatu> MassRescheduleStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupReminder> PickupReminders { get; set; }
        public virtual PickupRouteType PickupRouteType { get; set; }
        public virtual Route Route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupScheduleRoute> PickupScheduleRoutes { get; set; }
    }
}
