//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupReminder
    {
        public int PickupReminderId { get; set; }
        public int ScheduleId { get; set; }
        public int PhoneScriptId { get; set; }
        public int DonationId { get; set; }
        public bool CanDonorBeCalled { get; set; }
        public int PickupReminderStatusId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string CallSID { get; set; }
        public Nullable<int> ReceivedPhoneResponseTypeId { get; set; }
        public Nullable<int> PickupReminderHistoryId { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual PhoneScript PhoneScript { get; set; }
        public virtual PickupReminderStatu PickupReminderStatu { get; set; }
        public virtual PickupSchedule PickupSchedule { get; set; }
        public virtual PickupReminderHistory PickupReminderHistory { get; set; }
    }
}
