//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Template_temp_new
    {
        public string HtmlOutput { get; set; }
        public Nullable<int> templateId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string userID { get; set; }
        public System.DateTime PrintDate { get; set; }
    }
}
