//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class send_log
    {
        public int id { get; set; }
        public string mobile { get; set; }
        public string sendtext { get; set; }
        public string response { get; set; }
        public string created { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
