//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignedDoc
    {
        public int Id { get; set; }
        public Nullable<int> LetterId { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> RefNo { get; set; }
        public string FileName { get; set; }
        public string FileLocation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
