//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp1
    {
        public decimal RECEIPT_ID { get; set; }
        public string PROPERTY_NUMBER { get; set; }
        public string PROP_REG_ID { get; set; }
        public string PROP_ID { get; set; }
        public string SECTOR { get; set; }
        public string BLOCK { get; set; }
        public string ALLOTE_NAME { get; set; }
        public string DEPOSETER_NAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> DEPT_ID { get; set; }
        public string BANK_ID { get; set; }
        public string CHALLAN_ID { get; set; }
        public System.DateTime DEPOSIT_DATE { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string USERID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string RID_NO { get; set; }
        public Nullable<System.DateTime> P_FROM_DATE { get; set; }
        public Nullable<System.DateTime> P_TO_DATE { get; set; }
        public string CONS_NO { get; set; }
        public string FLAG_EDIT { get; set; }
        public string GST_NO { get; set; }
    }
}
