//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TjskServidept
    {
        public Nullable<int> ServiceId { get; set; }
        public string ServiceName { get; set; }
        public int departmentId { get; set; }
        public Nullable<int> TotalReceived { get; set; }
        public Nullable<int> WithDrawn { get; set; }
        public Nullable<int> CompletedWithinTime { get; set; }
        public Nullable<int> CompletedBeyondTime { get; set; }
        public Nullable<int> PendingWithTime { get; set; }
        public Nullable<int> PendingMoreThanWeek { get; set; }
        public Nullable<int> PendingMoreThanFortNight { get; set; }
        public Nullable<int> PendingMoreThanOneMonth { get; set; }
        public Nullable<int> TotalReject { get; set; }
        public Nullable<int> TotalObjection { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
