//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmUserSerialMaster
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string CertificateSerialNo { get; set; }
        public string CertificateName { get; set; }
        public string CertificatePhoneNo { get; set; }
    }
}
