//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public Nullable<int> schemeId { get; set; }
        public string schemeName { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string departmentName { get; set; }
        public string formNo { get; set; }
        public string tFirstName { get; set; }
        public string tMiddleName { get; set; }
        public string tLastName { get; set; }
        public string tGender { get; set; }
        public string tFatherHusbandName { get; set; }
        public string tSigningAuthority { get; set; }
        public string tCorrespondanceAdd { get; set; }
        public string tMobileNumber { get; set; }
        public string T_Company_Name { get; set; }
        public Nullable<System.DateTime> allotmentDate { get; set; }
        public string sectorName { get; set; }
        public string blockName { get; set; }
        public int rid { get; set; }
        public Nullable<int> propertyId { get; set; }
        public string propertyNo { get; set; }
        public Nullable<decimal> landRatePerSqmt { get; set; }
        public Nullable<decimal> totalArea { get; set; }
        public Nullable<decimal> totalPropertyCost { get; set; }
    }
}
