//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewReceiptMaster_old
    {
        public string RECEIPT_ID { get; set; }
        public Nullable<decimal> RECEIPT_HEAD_ID { get; set; }
        public Nullable<decimal> RECEIPT_SUBHEAD_ID { get; set; }
        public string PROPERTY_NUMBER { get; set; }
        public Nullable<int> PROP_ID { get; set; }
        public string RID_NO { get; set; }
        public Nullable<int> ALLOTE_NAME { get; set; }
        public Nullable<int> DEPT_CODE { get; set; }
        public string CHALLAN_ID { get; set; }
        public Nullable<decimal> AMOUNT_PAID { get; set; }
        public Nullable<System.DateTime> DEPOSIT_DATE { get; set; }
        public int STATUS { get; set; }
        public int USERID { get; set; }
        public Nullable<System.DateTime> asENTRY_DATE { get; set; }
        public Nullable<int> P_FROM_DATE { get; set; }
        public Nullable<int> P_TO_DATE { get; set; }
        public Nullable<int> CONS_NO { get; set; }
        public string RECIEPT_HEAD_NAME { get; set; }
        public string RECEIPT_SUB_HEAD { get; set; }
    }
}
