//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noida.Authority.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSiteDonation
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> AddressNumber { get; set; }
        public string AddressStreet { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string CrossStreet { get; set; }
        public Nullable<int> ItemLocationID { get; set; }
        public Nullable<int> ResidenceTypeID { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public string Instructions { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsSMSPreferred { get; set; }
        public bool IsEmailPreferred { get; set; }
        public bool IsPhonePreferred { get; set; }
        public Nullable<int> ScheduleID { get; set; }
    }
}
